import { mkdirSync, writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { intentColors, semanticColors } from "./colors.js"
import { duration, easing } from "./motion.js"

const __dirname = dirname(fileURLToPath(import.meta.url))

type NestedRecord = Record<string, Record<string, string>>

function generateVars(prefix: string, obj: NestedRecord): string {
  return Object.entries(obj)
    .flatMap(([group, values]) =>
      Object.entries(values).map(
        ([key, value]) => `  --${prefix}-${group}-${key}: ${value};`
      )
    )
    .join("\n")
}

function generateIntentVars(intents: NestedRecord): string {
  return Object.entries(intents)
    .flatMap(([intent, values]) =>
      Object.entries(values).map(
        ([key, value]) => `  --intent-${intent}-${key}: ${value};`
      )
    )
    .join("\n")
}

const css = `/* Auto-generated by @nacalui/tokens — do not edit */
:root {
${generateVars("color", semanticColors.light)}
${generateIntentVars(intentColors.light)}
${Object.entries(duration)
  .map(([k, v]) => `  --duration-${k}: ${v};`)
  .join("\n")}
${Object.entries(easing)
  .map(([k, v]) => `  --easing-${k}: ${v};`)
  .join("\n")}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${generateVars("color", semanticColors.dark)}
${generateIntentVars(intentColors.dark)}
  }
}

:root[data-theme="dark"] {
${generateVars("color", semanticColors.dark)}
${generateIntentVars(intentColors.dark)}
}
`

const outDir = resolve(__dirname, "..")
mkdirSync(outDir, { recursive: true })
writeFileSync(resolve(outDir, "tokens.css"), css)
// biome-ignore lint/suspicious/noConsole: build script output
console.log("Generated dist/tokens.css")
